### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by doubleAAbat** [omgimanerd/maplestory-bot#3]
Hey, does this work on Windows 10? I am having trouble getting it to press. I am tech savvy just do not know why commands are not pressing keys on OSK? Thanks in advance, big fan of this =)

**Comment by omgimanerd** [comment]
Hi there, this uses the pyautogui module to press keys on the On Screen Keyboard. I'd suggest first checking to see if the individual pyautogui commands work. This was designed for Win7's OSK so you're probably going to have to set different mouse coordinates for the different keys.

**Comment by doubleAAbat** [comment]
Hey, thanks for quickly responding! I wrote this simple script to try and first get any of the button clicks to register in the game. I can see the python script working and hovering over the OSK. However, it fails to actually click on any of the bottons with click() or mouseDown(). I have tried using different keys, and messing with commands, but nothing seems to get the OSK on Windows 10 to click after the mouse hovering over the key. 

import pyautogui
import time

pgdown = [1250,650]
pgup = [1250, 630]
right = [1120, 710]
down = [1100, 710]
left = [1080, 710]
up = [1100, 700]
space = [1000, 710]
alt = [890, 710]

time.sleep(3)
pyautogui.moveTo(300,300)
pyautogui.click(300,300)

time.sleep(2)
pyautogui.moveTo(alt)
pyautogui.mouseDown()
time.sleep(0.5)
pyautogui.mouseUp()
time.sleep(.2)

**Comment by omgimanerd** [comment]
According to the [documentation](http://pyautogui.readthedocs.io/en/latest/mouse.html#mouse-clicks), you need to invoke `pyautogui.click()` to click, and the parameters are passed using kwargs and not as regular arguments. Example:
```
pyautogui.click(x=300,y=300)
```
I'm not sure why the `mouseDown()` and `mouseUp()` functions wouldn't work though. It might be a Windows 10 specific thing. Try running the script as administrator.

**Comment by doubleAAbat** [comment]
Thanks! Danggggg, long struggle but seems like the Windows 10 OSK does not accept the click for some reason. I downloaded another virtual keyboard and it works on there! I believe since this other virtual keyboard is still not connected to ms in any way there is still no worry of getting banned, but I could be wrong.

**Comment by omgimanerd** [comment]
MapleStory has no way to detect this since you're not packet sniffing or injecting packets. However, if a GM comes by and sees you repeating an action over and over you might get banned. It depends. I haven't been banned and I ran this for 300 hours once.

**Comment by jstoebe** [comment]
Correct me if I'm wrong, I remember if I didn't run the python script as administrator I had issues with pyautogui sometime not clicking correctly.

**Comment by doubleAAbat** [comment]
Thanks for much man!

**Comment by doubleAAbat** [comment]
Also, I have been experimenting with the press() function instead of using the OSK, to your knowledge is that banable, it is pressing the keys I would guess on a level above the OS so I doubt it would be catchable. What is your take? Using the press() function in the pyautogui gets rid of the need to use the OSK and is more programmable as you can press multiple keys at the same time.

**Comment by omgimanerd** [comment]
So from what I can determine, the `press()` functions operate on a software level that can't even be received by MapleStory (that or they're deliberately filtered out). I've tried it, actions inputted using the `press()` function aren't registered by the program. That's the entire reason why we use the OSK instead.
